/**
 * Conversation Types
 * Types for conversation management, branching, and tagging
 */

import { Message } from './index';

export interface ConversationTag {
  id: string;
  name: string;
  color: string; // Tailwind color class (e.g., 'blue', 'green', 'purple')
  icon?: string; // Emoji or icon
}

export interface ConversationBranch {
  id: string;
  conversationId: string;
  parentBranchId?: string; // null for main branch
  branchPointMessageIndex: number; // Which message this branched from
  title: string;
  createdAt: Date;
  lastMessageAt: Date;
  messageCount: number;
}

export interface Conversation {
  id: string;
  title: string;
  autoGeneratedTitle?: string; // AI-generated title
  customTitle?: string; // User-edited title
  tags: ConversationTag[];
  messages: Message[];
  branches: ConversationBranch[];
  currentBranchId: string; // Which branch is active
  createdAt: Date;
  updatedAt: Date;
  lastMessageAt: Date;
  messageCount: number;
  isArchived: boolean;
  isPinned: boolean;
}

export interface ConversationMetadata {
  id: string;
  title: string;
  tags: ConversationTag[];
  createdAt: Date;
  updatedAt: Date;
  lastMessageAt: Date;
  messageCount: number;
  branchCount: number;
  isArchived: boolean;
  isPinned: boolean;
  firstMessagePreview: string; // First 100 chars of first message
}

export interface ConversationFilter {
  searchQuery?: string;
  tags?: string[]; // Filter by tag IDs
  dateRange?: {
    start: Date;
    end: Date;
  };
  isArchived?: boolean;
  isPinned?: boolean;
}

export interface ConversationSortOption {
  field: 'updatedAt' | 'createdAt' | 'title' | 'messageCount';
  direction: 'asc' | 'desc';
}

// Predefined tag colors
export const TAG_COLORS: Record<string, string> = {
  work: 'blue',
  personal: 'green',
  creative: 'purple',
  research: 'orange',
  learning: 'yellow',
  coding: 'indigo',
  tasks: 'red',
  notes: 'gray',
};

// Default tags
export const DEFAULT_TAGS: ConversationTag[] = [
  { id: 'work', name: 'Work', color: 'blue', icon: '💼' },
  { id: 'personal', name: 'Personal', color: 'green', icon: '🏠' },
  { id: 'creative', name: 'Creative', color: 'purple', icon: '🎨' },
  { id: 'research', name: 'Research', color: 'orange', icon: '📚' },
  { id: 'learning', name: 'Learning', color: 'yellow', icon: '📖' },
  { id: 'coding', name: 'Coding', color: 'indigo', icon: '💻' },
  { id: 'tasks', name: 'Tasks', color: 'red', icon: '✅' },
  { id: 'notes', name: 'Notes', color: 'gray', icon: '📝' },
];
